### ISSUE TITLE
Does this pkg support holonomic velocity smooth ?

### ISSUE THREAD

**Issue by hoppss** [unirlm/holonomic_velocity_smoother#1]
I set holonomic param for true, 
the output twist doesnot smooth linear.y

**Comment by unirlm** [comment]
for holonomic you need to use the "/holonomic_smooth_cmd_vel" topic

**Comment by unirlm** [comment]
> I set holonomic param for true,
> the output twist doesnot smooth linear.y

for holonomic you need to use the "/holonomic_smooth_cmd_vel" topic

**Comment by hoppss** [comment]
thank you
